name: build

on: 
  workflow_dispatch:

env:
  NDK_VERSION: 29.0.14206865
  MIN_SDK_VERSION: 21

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache NDK
        id: ndk-cache
        uses: actions/cache@v3
        with:
          path: ndk
          key: ndk-${{ env.NDK_VERSION }}
          restore-keys: |
            ndk-${{ env.NDK_VERSION }}

      - name: Install NDK
        if: steps.ndk-cache.outputs.cache-hit != 'true'
        run: |
          echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;${{ env.NDK_VERSION }}"
          sudo cp -r $ANDROID_HOME/ndk/${{ env.NDK_VERSION }} ndk
          ME=$(whoami)
          sudo chown -R $ME:$ME ndk

      - name: Set NDK environment variable
        run: echo "ANDROID_NDK_HOME=$(pwd)/ndk" >> $GITHUB_ENV

      - name: Build
        run: |
          make libs
          make zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: magisk modules
          path: out/*.zip
